In [1]:
from urllib import response

import pandas as pd
from packaging.utils import parse_wheel_filename

In [2]:
vessels = pd.read_csv('../data/shadow_fleet_vessels.csv')
print(vessels.shape)
vessels.head()

(50, 9)

,imo,vessel_name,tanker_size,build_year,flag,ship_manager,registered_owner,ism_manager,list_source
0,9328170,Aether,Aframax,2007,Unknown,UAE. Zulu Ships Management,UAE. Wrasse Ship Co,UAE. Zulu Ships Management,new_crude_2025
1,9282481,Tagor,Aframax,2005,Unknown,UAE. Zulu Ships Management,UAE. Blaire Charters Ltd,UAE. Tarabya Logistics Ltd,new_crude_2025
2,9236248,Phoenix I,Aframax,2002,Comoros,UAE. Triviality Shipping Llc,UAE. Celestial Overseas Co Ltd,UAE. Triviality Shipping Llc,new_crude_2025
3,9439383,Bhilva,Aframax,2010,Panama,Seychelles. Tika Shipping Ltd,Seychelles. Tika Shipping Ltd,China. Song Hua Jiang Shipmanagement,new_crude_2025
4,9311610,Torx,Suezmax,2006,Panama,Seychelles. Shiva Shipping Ltd,Seychelles. Shiva Shipping Ltd,Singapore. Crest Maritime Pte Ltd,new_crude_2025

In [3]:
import os
from dotenv import load_dotenv

load_dotenv()

token = os.getenv("GFW_API_TOKEN")
print("token loaded:", token is not None and len(token) > 20)

token loaded: True

In [4]:
import requests
headers = {
    "Authorization": f"Bearer {token}"
}
imo_test = "9328170"
url = f"https://gateway.api.globalfishingwatch.org/v3/vessels/search"
params = {
    "query": imo_test,
    "datasets[0]": "public-global-vessel-identity:latest"
}

response = requests.get(url, headers=headers, params=params)
print("status", response.status_code)
data = response.json()
data

status 200

{'limit': 30,
 'since': None,
 'total': 7,
 'entries': [{'dataset': 'public-global-vessel-identity:v4.0',
   'registryInfoTotalRecords': 1,
   'registryInfo': [{'id': '3f4aa69a84a907927d2d005eedfc209a',
     'sourceCode': ['TMT_OTHER'],
     'ssvid': '352002230',
     'flag': 'PAN',
     'shipname': 'AETHER',
     'nShipname': 'AETHER',
     'callsign': '3E2221',
     'imo': '9328170',
     'latestVesselInfo': True,
     'transmissionDateFrom': '2023-01-23T14:38:25Z',
     'transmissionDateTo': '2025-10-06T11:09:01Z',
     'lengthM': None,
     'tonnageGt': None,
     'vesselInfoReference': 'e974a02026523f16c8fb65f7f2418021',
     'extraFields': [{'registrySource': 'TMT',
       'iuuStatus': {'value': None,
        'dateFrom': None,
        'dateFromMask': None,
        'dateTo': None,
        'dateToMask': None},
       'hasComplianceInfo': None,
       'images': [],
       'operator': None,
       'builtYear': {'value': None,
        'dateFrom': None,
        'dateFromMask': None,
        'dateTo': None,
        'dateToMask': None},
       'depthM': {'value': None,
        'dateFrom': None,
        'dateFromMask': None,
        'dateTo': None,
        'dateToMask': None}}]}],
   'registryOwners': [],
   'combinedSourcesInfo': [{'vesselId': '7868780d4-4d3b-af4d-e93f-543eb7165251',
     'geartypes': [{'name': 'OTHER',
       'source': 'COMBINATION_OF_REGISTRY_AND_AIS_INFERRED_NN_INFO',
       'yearFrom': 2023,
       'yearTo': 2025}],
     'shiptypes': [{'name': 'OTHER',
       'source': 'COMBINATION_OF_REGISTRY_AND_AIS_INFERRED_NN_INFO',
       'yearFrom': 2023,
       'yearTo': 2025}]}],
   'selfReportedInfo': [{'id': '7868780d4-4d3b-af4d-e93f-543eb7165251',
     'ssvid': '352002230',
     'shipname': 'AETHER',
     'nShipname': 'AETHER',
     'flag': 'PAN',
     'callsign': '3E2221',
     'imo': '9328170',
     'messagesCounter': 3896515,
     'positionsCounter': 975552,
     'sourceCode': ['AIS'],
     'matchFields': 'SEVERAL_FIELDS',
     'transmissionDateFrom': '2023-01-23T14:37:09Z',
     'transmissionDateTo': '2025-11-02T11:08:24Z'}]},
  {'dataset': 'public-global-vessel-identity:v4.0',
   'registryInfoTotalRecords': 1,
   'registryInfo': [{'id': 'b4668a61ad93f598b819afa780bd0254',
     'sourceCode': ['IMO'],
     'ssvid': '447162000',
     'flag': 'KWT',
     'shipname': 'WAFRAH',
     'nShipname': 'WAFRAH',
     'callsign': '9KEG',
     'imo': '9328170',
     'latestVesselInfo': True,
     'transmissionDateFrom': '2012-01-08T14:12:44Z',
     'transmissionDateTo': '2022-05-10T11:17:25Z',
     'geartypes': ['TANKER'],
     'lengthM': None,
     'tonnageGt': 63440,
     'vesselInfoReference': '102f973c31ac57d0ecb16b886cf6a038',
     'extraFields': []}],
   'registryOwners': [],
   'combinedSourcesInfo': [{'vesselId': '78665b4b3-3f81-f746-90aa-e0a28c06e1d5',
     'geartypes': [{'name': 'OTHER',
       'source': 'COMBINATION_OF_REGISTRY_AND_AIS_INFERRED_NN_INFO',
       'yearFrom': 2012,
       'yearTo': 2022}],
     'shiptypes': [{'name': 'OTHER',
       'source': 'COMBINATION_OF_REGISTRY_AND_AIS_INFERRED_NN_INFO',
       'yearFrom': 2012,
       'yearTo': 2022}]}],
   'selfReportedInfo': [{'id': '78665b4b3-3f81-f746-90aa-e0a28c06e1d5',
     'ssvid': '447162000',
     'shipname': 'WAFRAH',
     'nShipname': 'WAFRAH',
     'flag': 'KWT',
     'callsign': '9KEG',
     'imo': '9328170',
     'messagesCounter': 1274500,
     'positionsCounter': 471887,
     'sourceCode': ['AIS'],
     'matchFields': 'SEVERAL_FIELDS',
     'transmissionDateFrom': '2012-01-06T10:49:54Z',
     'transmissionDateTo': '2022-05-10T11:22:29.7Z'}]},
  {'dataset': 'public-global-vessel-identity:v4.0',
   'registryInfoTotalRecords': 0,
   'registryInfo': [],
   'registryOwners': [],
   'combinedSourcesInfo': [{'vesselId': '31efe1c63-3ce5-f93d-850c-90a3008a6c54',
     'geartypes': [{'name': 'OTHER',
       'source': 'COMBINATION_OF_REGISTRY_AND_AIS_INFERRED_NN_INFO',
       'yearFrom': 2026,
       'yearTo': 2026}],
     'shiptypes': [{'name': 'OTHER',
       'source': 'COMBINATION_OF_REGISTRY_AND_AIS_INFERRED_NN_INFO',
       'yearFrom': 2026,
       'yearTo': 2026}]}],
   'selfReportedInfo': [{'id': '31efe1c63-3ce5-f93d-850c-90a3008a6c54',
     'ssvid': '647553007',
     'shipname': 'AETHER',
     'nShipname': 'AETHER',
     'flag': 'MDG',
     'callsign': '5RA07',
     'imo': '9328170',
     'messagesCounter': 622203,
     'positionsCounter': 63204,
     'sourceCode': ['AIS'],
     'matchFields': 'NO_MATCH',
     'transmissionDateFrom': '2026-03-14T15:43:17Z',
     'transmissionDateTo': '2026-05-19T14:51:02Z'}]},
  {'dataset': 'public-global-vessel-identity:v4.0',
   'registryInfoTotalRecords': 0,
   'registryInfo': [],
   'registryOwners': [],
   'combinedSourcesInfo': [{'vesselId': '2ab9e5bb0-0e70-0344-cc39-6d8b674a60d6',
     'geartypes': [{'name': 'OTHER',
       'source': 'COMBINATION_OF_REGISTRY_AND_AIS_INFERRED_NN_INFO',
       'yearFrom': 2025,
       'yearTo': 2026}],
     'shiptypes': [{'name': 'OTHER',
       'source': 'COMBINATION_OF_REGISTRY_AND_AIS_INFERRED_NN_INFO',
       'yearFrom': 2025,
       'yearTo': 2026}]}],
   'selfReportedInfo': [{'id': '2ab9e5bb0-0e70-0344-cc39-6d8b674a60d6',
     'ssvid': '632001155',
     'shipname': 'AETHER',
     'nShipname': 'AETHER',
     'flag': 'GIN',
     'callsign': '3X2128',
     'imo': '9328170',
     'messagesCounter': 526794,
     'positionsCounter': 168781,
     'sourceCode': ['AIS'],
     'matchFields': 'NO_MATCH',
     'transmissionDateFrom': '2025-10-06T11:17:25Z',
     'transmissionDateTo': '2026-03-14T15:49:37Z'}]},
  {'dataset': 'public-global-vessel-identity:v4.0',
   'registryInfoTotalRecords': 0,
   'registryInfo': [],
   'registryOwners': [],
   'combinedSourcesInfo': [{'vesselId': 'e6ea4eb5f-f346-4c12-d412-282d70689b0a',
     'geartypes': [{'name': 'OTHER',
       'source': 'COMBINATION_OF_REGISTRY_AND_AIS_INFERRED_NN_INFO',
       'yearFrom': 2026,
       'yearTo': 2026}],
     'shiptypes': [{'name': 'OTHER',
       'source': 'COMBINATION_OF_REGISTRY_AND_AIS_INFERRED_NN_INFO',
       'yearFrom': 2026,
       'yearTo': 2026}]}],
   'selfReportedInfo': [{'id': 'e6ea4eb5f-f346-4c12-d412-282d70689b0a',
     'ssvid': '613442802',
     'shipname': 'AETHER',
     'nShipname': 'AETHER',
     'flag': 'CMR',
     'callsign': 'TJM91N',
     'imo': '9328170',
     'messagesCounter': 11707,
     'positionsCounter': 549,
     'sourceCode': ['AIS'],
     'matchFields': 'NO_MATCH',
     'transmissionDateFrom': '2026-05-19T14:56:47Z',
     'transmissionDateTo': '2026-05-20T07:55:53Z'}]},
  {'dataset': 'public-global-vessel-identity:v4.0',
   'registryInfoTotalRecords': 0,
   'registryInfo': [],
   'registryOwners': [],
   'combinedSourcesInfo': [{'vesselId': 'd67012d4a-a995-0f7b-97e1-521310fc728f',
     'geartypes': [{'name': 'OTHER',
       'source': 'COMBINATION_OF_REGISTRY_AND_AIS_INFERRED_NN_INFO',
       'yearFrom': 2022,
       'yearTo': 2023}],
     'shiptypes': [{'name': 'OTHER',
       'source': 'COMBINATION_OF_REGISTRY_AND_AIS_INFERRED_NN_INFO',
       'yearFrom': 2022,
       'yearTo': 2023}]}],
   'selfReportedInfo': [{'id': 'd67012d4a-a995-0f7b-97e1-521310fc728f',
     'ssvid': '636021839',
     'shipname': 'LILA FUJAIRAH',
     'nShipname': 'LILAFUJAIRAH',
     'flag': 'LBR',
     'callsign': '5LFY6',
     'imo': '9328170',
     'messagesCounter': 392095,
     'positionsCounter': 161922,
     'sourceCode': ['AIS'],
     'matchFields': 'NO_MATCH',
     'transmissionDateFrom': '2022-05-10T11:31:35.73Z',
     'transmissionDateTo': '2023-02-18T05:12:21Z'}]},
  {'dataset': 'public-global-vessel-identity:v4.0',
   'registryInfoTotalRecords': 0,
   'registryInfo': [],
   'registryOwners': [],
   'combinedSourcesInfo': [{'vesselId': '26ad54a75-54de-13fe-5c0e-1a7a3b1d63cf',
     'geartypes': [{'name': 'OTHER',
       'source': 'COMBINATION_OF_REGISTRY_AND_AIS_INFERRED_NN_INFO',
       'yearFrom': 2026,
       'yearTo': 2026}],
     'shiptypes': [{'name': 'OTHER',
       'source': 'COMBINATION_OF_REGISTRY_AND_AIS_INFERRED_NN_INFO',
       'yearFrom': 2026,
       'yearTo': 2026}]}],
   'selfReportedInfo': [{'id': '26ad54a75-54de-13fe-5c0e-1a7a3b1d63cf',
     'ssvid': '613442803',
     'shipname': 'AETHER',
     'nShipname': 'AETHER',
     'flag': 'CMR',
     'callsign': 'TJM91N',
     'imo': '9328170',
     'messagesCounter': 12493697,
     'positionsCounter': 571095,
     'sourceCode': ['AIS'],
     'matchFields': 'NO_MATCH',
     'transmissionDateFrom': '2026-05-20T08:24:58Z',
     'transmissionDateTo': '2026-08-14T23:59:58Z'}]}],
 'metadata': {'query': '9328170',
  'normalizedQuery': '9328170',
  'didYouMean': {}}}

In [5]:
def get_vessel_info(imo):
    url = "https://gateway.api.globalfishingwatch.org/v3/vessels/search"
    params = {
        "query": imo,
        "datasets[0]": "public-global-vessel-identity:latest"
    }
    response = requests.get(url, headers=headers, params=params)

    if response.status_code != 200:
        print(f"Error for imo {imo}: status code {response.status_code}")
        return None
    return response.json()

In [6]:
result = get_vessel_info("9282481")
result

{'limit': 30,
 'since': None,
 'total': 8,
 'entries': [{'dataset': 'public-global-vessel-identity:v4.0',
   'registryInfoTotalRecords': 1,
   'registryInfo': [{'id': 'b7fd24234754a83983fe30f270904aca',
     'sourceCode': ['TMT_OTHER'],
     'ssvid': '352002249',
     'flag': 'PAN',
     'shipname': 'TAGOR',
     'nShipname': 'TAGOR',
     'callsign': '3E2235',
     'imo': '9282481',
     'latestVesselInfo': True,
     'transmissionDateFrom': '2024-07-06T08:23:17Z',
     'transmissionDateTo': '2025-09-12T05:12:57Z',
     'lengthM': None,
     'tonnageGt': None,
     'vesselInfoReference': '5b0b2edf826c8b7f49b49c48cef20593',
     'extraFields': [{'registrySource': 'TMT',
       'iuuStatus': {'value': None,
        'dateFrom': None,
        'dateFromMask': None,
        'dateTo': None,
        'dateToMask': None},
       'hasComplianceInfo': None,
       'images': [],
       'operator': None,
       'builtYear': {'value': None,
        'dateFrom': None,
        'dateFromMask': None,
        'dateTo': None,
        'dateToMask': None},
       'depthM': {'value': None,
        'dateFrom': None,
        'dateFromMask': None,
        'dateTo': None,
        'dateToMask': None}}]}],
   'registryOwners': [],
   'combinedSourcesInfo': [{'vesselId': 'e343b1da5-5b7a-de04-e72f-279e95210584',
     'geartypes': [{'name': 'OTHER',
       'source': 'COMBINATION_OF_REGISTRY_AND_AIS_INFERRED_NN_INFO',
       'yearFrom': 2023,
       'yearTo': 2025}],
     'shiptypes': [{'name': 'OTHER',
       'source': 'COMBINATION_OF_REGISTRY_AND_AIS_INFERRED_NN_INFO',
       'yearFrom': 2023,
       'yearTo': 2025}]}],
   'selfReportedInfo': [{'id': 'e343b1da5-5b7a-de04-e72f-279e95210584',
     'ssvid': '352002249',
     'shipname': 'TAGOR',
     'nShipname': 'TAGOR',
     'flag': 'PAN',
     'callsign': '3E2235',
     'imo': '9282481',
     'messagesCounter': 2863780,
     'positionsCounter': 760869,
     'sourceCode': ['AIS'],
     'matchFields': 'SEVERAL_FIELDS',
     'transmissionDateFrom': '2023-01-18T01:58:22Z',
     'transmissionDateTo': '2025-09-22T06:28:48Z'}]},
  {'dataset': 'public-global-vessel-identity:v4.0',
   'registryInfoTotalRecords': 1,
   'registryInfo': [{'id': 'd725f287100262cc92839c01538f2c61',
     'sourceCode': ['IMO'],
     'ssvid': '232150000',
     'flag': 'IMN',
     'shipname': 'BRITISHGANNET',
     'nShipname': 'BRITISHGANNET',
     'callsign': 'MGRX9',
     'imo': '9282481',
     'latestVesselInfo': True,
     'transmissionDateFrom': '2012-01-13T03:59:15Z',
     'transmissionDateTo': '2018-12-12T13:10:10Z',
     'geartypes': ['TANKER'],
     'lengthM': None,
     'tonnageGt': 63661,
     'vesselInfoReference': 'e3c70e4d65921ca4d4d26f7482e30e82',
     'extraFields': []}],
   'registryOwners': [],
   'combinedSourcesInfo': [{'vesselId': 'c0830f34f-ff65-a8f1-62c9-1f0e4b069ae5',
     'geartypes': [{'name': 'OTHER',
       'source': 'COMBINATION_OF_REGISTRY_AND_AIS_INFERRED_NN_INFO',
       'yearFrom': 2012,
       'yearTo': 2018}],
     'shiptypes': [{'name': 'OTHER',
       'source': 'COMBINATION_OF_REGISTRY_AND_AIS_INFERRED_NN_INFO',
       'yearFrom': 2012,
       'yearTo': 2018}]}],
   'selfReportedInfo': [{'id': 'c0830f34f-ff65-a8f1-62c9-1f0e4b069ae5',
     'ssvid': '232150000',
     'shipname': 'BRITISH GANNET',
     'nShipname': 'BRITISHGANNET',
     'flag': 'GBR',
     'callsign': 'MGRX9',
     'imo': '9282481',
     'messagesCounter': 580959,
     'positionsCounter': 298018,
     'sourceCode': ['AIS'],
     'matchFields': 'SEVERAL_FIELDS',
     'transmissionDateFrom': '2012-01-04T17:14:53Z',
     'transmissionDateTo': '2018-12-12T13:07:00Z'}]},
  {'dataset': 'public-global-vessel-identity:v4.0',
   'registryInfoTotalRecords': 0,
   'registryInfo': [],
   'registryOwners': [],
   'combinedSourcesInfo': [{'vesselId': '1ff0ec2ce-ef7a-75f9-7c67-38abeb4f9207',
     'geartypes': [{'name': 'OTHER',
       'source': 'COMBINATION_OF_REGISTRY_AND_AIS_INFERRED_NN_INFO',
       'yearFrom': 2018,
       'yearTo': 2023}],
     'shiptypes': [{'name': 'OTHER',
       'source': 'COMBINATION_OF_REGISTRY_AND_AIS_INFERRED_NN_INFO',
       'yearFrom': 2018,
       'yearTo': 2023}]}],
   'selfReportedInfo': [{'id': '1ff0ec2ce-ef7a-75f9-7c67-38abeb4f9207',
     'ssvid': '538008199',
     'shipname': 'PIPER',
     'nShipname': 'PIPER',
     'flag': 'MHL',
     'callsign': 'V7A2072',
     'imo': '9282481',
     'messagesCounter': 2131027,
     'positionsCounter': 769548,
     'sourceCode': ['AIS'],
     'matchFields': 'NO_MATCH',
     'transmissionDateFrom': '2018-12-12T13:16:50Z',
     'transmissionDateTo': '2023-02-04T23:21:30Z'}]},
  {'dataset': 'public-global-vessel-identity:v4.0',
   'registryInfoTotalRecords': 0,
   'registryInfo': [],
   'registryOwners': [],
   'combinedSourcesInfo': [{'vesselId': '779363393-3c4a-27ae-e75c-568791c59948',
     'geartypes': [{'name': 'OTHER',
       'source': 'COMBINATION_OF_REGISTRY_AND_AIS_INFERRED_NN_INFO',
       'yearFrom': 2026,
       'yearTo': 2026}],
     'shiptypes': [{'name': 'OTHER',
       'source': 'COMBINATION_OF_REGISTRY_AND_AIS_INFERRED_NN_INFO',
       'yearFrom': 2026,
       'yearTo': 2026}]}],
   'selfReportedInfo': [{'id': '779363393-3c4a-27ae-e75c-568791c59948',
     'ssvid': '613442790',
     'shipname': 'TAGOR',
     'nShipname': 'TAGOR',
     'flag': 'CMR',
     'callsign': 'TJM51A',
     'imo': '9282481',
     'messagesCounter': 2848687,
     'positionsCounter': 207469,
     'sourceCode': ['AIS'],
     'matchFields': 'NO_MATCH',
     'transmissionDateFrom': '2026-05-26T10:02:57Z',
     'transmissionDateTo': '2026-08-14T23:57:07Z'}]},
  {'dataset': 'public-global-vessel-identity:v4.0',
   'registryInfoTotalRecords': 0,
   'registryInfo': [],
   'registryOwners': [],
   'combinedSourcesInfo': [{'vesselId': '97776be53-3f32-2f42-0439-c5cb44cc945d',
     'geartypes': [{'name': 'OTHER',
       'source': 'COMBINATION_OF_REGISTRY_AND_AIS_INFERRED_NN_INFO',
       'yearFrom': 2026,
       'yearTo': 2026}],
     'shiptypes': [{'name': 'OTHER',
       'source': 'COMBINATION_OF_REGISTRY_AND_AIS_INFERRED_NN_INFO',
       'yearFrom': 2026,
       'yearTo': 2026}]}],
   'selfReportedInfo': [{'id': '97776be53-3f32-2f42-0439-c5cb44cc945d',
     'ssvid': '647260300',
     'shipname': 'TAGOR',
     'nShipname': 'TAGOR',
     'flag': 'MDG',
     'callsign': '5RA000',
     'imo': '9282481',
     'messagesCounter': 90640,
     'positionsCounter': 26705,
     'sourceCode': ['AIS'],
     'matchFields': 'NO_MATCH',
     'transmissionDateFrom': '2026-03-17T05:45:02Z',
     'transmissionDateTo': '2026-05-26T08:33:12Z'}]},
  {'dataset': 'public-global-vessel-identity:v4.0',
   'registryInfoTotalRecords': 0,
   'registryInfo': [],
   'registryOwners': [],
   'combinedSourcesInfo': [{'vesselId': '3b359ae29-977a-8747-4fe7-0f0f79269db8',
     'geartypes': [{'name': 'OTHER',
       'source': 'COMBINATION_OF_REGISTRY_AND_AIS_INFERRED_NN_INFO',
       'yearFrom': 2025,
       'yearTo': 2026}],
     'shiptypes': [{'name': 'OTHER',
       'source': 'COMBINATION_OF_REGISTRY_AND_AIS_INFERRED_NN_INFO',
       'yearFrom': 2025,
       'yearTo': 2026}]}],
   'selfReportedInfo': [{'id': '3b359ae29-977a-8747-4fe7-0f0f79269db8',
     'ssvid': '632001144',
     'shipname': 'TAGOR',
     'nShipname': 'TAGOR',
     'flag': 'GIN',
     'callsign': '3X2117',
     'imo': '9282481',
     'messagesCounter': 712415,
     'positionsCounter': 194980,
     'sourceCode': ['AIS'],
     'matchFields': 'NO_MATCH',
     'transmissionDateFrom': '2025-09-15T11:54:24Z',
     'transmissionDateTo': '2026-03-17T05:41:01Z'}]},
  {'dataset': 'public-global-vessel-identity:v4.0',
   'registryInfoTotalRecords': 0,
   'registryInfo': [],
   'registryOwners': [],
   'combinedSourcesInfo': [{'vesselId': '20c2c5af0-044e-1a07-536f-ebe21ab350b3',
     'geartypes': [{'name': 'OTHER',
       'source': 'COMBINATION_OF_REGISTRY_AND_AIS_INFERRED_NN_INFO',
       'yearFrom': 2023,
       'yearTo': 2023}],
     'shiptypes': [{'name': 'OTHER',
       'source': 'COMBINATION_OF_REGISTRY_AND_AIS_INFERRED_NN_INFO',
       'yearFrom': 2023,
       'yearTo': 2023}]}],
   'selfReportedInfo': [{'id': '20c2c5af0-044e-1a07-536f-ebe21ab350b3',
     'ssvid': '350002249',
     'shipname': 'PRIAPUS',
     'nShipname': 'PRIAPUS',
     'flag': 'NIC',
     'callsign': '3E2235',
     'imo': '9282481',
     'messagesCounter': 499459,
     'positionsCounter': 54860,
     'sourceCode': ['AIS'],
     'matchFields': 'NO_MATCH',
     'transmissionDateFrom': '2023-04-03T12:56:44Z',
     'transmissionDateTo': '2023-06-11T06:36:00Z'}]},
  {'dataset': 'public-global-vessel-identity:v4.0',
   'registryInfoTotalRecords': 0,
   'registryInfo': [],
   'registryOwners': [],
   'combinedSourcesInfo': [{'vesselId': 'a4ab02c0f-f6ed-739d-2413-54991555104c',
     'geartypes': [{'name': 'OTHER',
       'source': 'COMBINATION_OF_REGISTRY_AND_AIS_INFERRED_NN_INFO',
       'yearFrom': 2012,
       'yearTo': 2012}],
     'shiptypes': [{'name': 'OTHER',
       'source': 'COMBINATION_OF_REGISTRY_AND_AIS_INFERRED_NN_INFO',
       'yearFrom': 2012,
       'yearTo': 2012}]}],
   'selfReportedInfo': [{'id': 'a4ab02c0f-f6ed-739d-2413-54991555104c',
     'ssvid': '228741000',
     'shipname': 'FRENCH NAVY WARSHIP',
     'nShipname': 'FRENCHNAVYWARSHIP',
     'flag': 'FRA',
     'callsign': 'FADC',
     'imo': '9282481',
     'messagesCounter': 212,
     'positionsCounter': 125,
     'sourceCode': ['AIS'],
     'matchFields': 'NO_MATCH',
     'transmissionDateFrom': '2012-03-13T17:13:44Z',
     'transmissionDateTo': '2012-03-21T06:01:13Z'}]}],
 'metadata': {'query': '9282481',
  'normalizedQuery': '9282481',
  'didYouMean': {}}}

In [15]:
def parse_vessel_data(imo, raw_data):
    if raw_data is None or raw_data['total'] == 0:
        return {"imo": imo, "found": False}, []

    all_identities = []

    for entry in raw_data['entries']:

        source_records = entry['registryInfo'] if entry['registryInfo'] else entry['selfReportedInfo']

        for record in source_records:
            all_identities.append({
                "imo": imo,
                "shipname": record.get('shipname'),
                "flag": record.get('flag'),
                "ssvid": record.get('ssvid'),
                "match_fields": record.get('matchFields', 'REGISTRY'),
                "transmission_from": record.get('transmissionDateFrom'),
                "transmission_to": record.get('transmissionDateTo'),
                "is_verified": record.get('matchFields') == 'SEVERAL_FIELDS' or 'sourceCode' in record and record.get('sourceCode') == ['IMO'],
            })

    # summary only verificated
    verified = [r for r in all_identities if r['is_verified']]
    current = max(verified, key=lambda r: r['transmission_to'] or '') if verified else all_identities[0]

    summary = {
        "imo": imo,
        "found": True,
        "current_name": current['shipname'],
        "current_flag": current['flag'],
        "num_total_identities": len(all_identities),
        "num_verified_identities": len(verified),
        "num_suspicious_matches": len(all_identities) - len(verified),
    }

    return summary, all_identities

In [18]:
summary, history = parse_vessel_data("9282481", result)
print(summary)

{'imo': '9282481', 'found': True, 'current_name': 'BRITISHGANNET', 'current_flag': 'IMN', 'num_total_identities': 8, 'num_verified_identities': 1, 'num_suspicious_matches': 7}

In [22]:
all_summaries = []
all_identities_full = []

for imo in vessels['imo']:
    raw = get_vessel_info(imo)
    summary, indentities = parse_vessel_data(imo, raw)
    all_summaries.append(summary)
    all_identities_full.extend(indentities)

In [24]:
for a in all_summaries:
    print(a)

{'imo': 9328170, 'found': True, 'current_name': 'WAFRAH', 'current_flag': 'KWT', 'num_total_identities': 7, 'num_verified_identities': 1, 'num_suspicious_matches': 6}
{'imo': 9282481, 'found': True, 'current_name': 'BRITISHGANNET', 'current_flag': 'IMN', 'num_total_identities': 8, 'num_verified_identities': 1, 'num_suspicious_matches': 7}
{'imo': 9236248, 'found': True, 'current_name': 'MINERVAZENIA', 'current_flag': 'GRC', 'num_total_identities': 7, 'num_verified_identities': 1, 'num_suspicious_matches': 6}
{'imo': 9439383, 'found': True, 'current_name': 'GIOVANNIBATTISTADECARLINI', 'current_flag': 'ITA', 'num_total_identities': 4, 'num_verified_identities': 1, 'num_suspicious_matches': 3}
{'imo': 9311610, 'found': True, 'current_name': 'MILTIADISM2', 'current_flag': 'LBR', 'num_total_identities': 3, 'num_verified_identities': 1, 'num_suspicious_matches': 2}
{'imo': 9472634, 'found': True, 'current_name': 'ADVANTAGEANTHEM', 'current_flag': 'MHL', 'num_total_identities': 2, 'num_verified_identities': 1, 'num_suspicious_matches': 1}
{'imo': 9460564, 'found': True, 'current_name': 'KALAMAS', 'current_flag': 'LBR', 'num_total_identities': 2, 'num_verified_identities': 1, 'num_suspicious_matches': 1}
{'imo': 9419450, 'found': True, 'current_name': 'ADVANTAGEAVENUE', 'current_flag': 'MHL', 'num_total_identities': 3, 'num_verified_identities': 1, 'num_suspicious_matches': 2}
{'imo': 9299707, 'found': True, 'current_name': 'GUANYIN', 'current_flag': 'LBR', 'num_total_identities': 5, 'num_verified_identities': 0, 'num_suspicious_matches': 5}
{'imo': 9296377, 'found': True, 'current_name': 'TOKYOSPIRIT', 'current_flag': 'BHS', 'num_total_identities': 5, 'num_verified_identities': 1, 'num_suspicious_matches': 4}
{'imo': 9224453, 'found': True, 'current_name': 'MARS A', 'current_flag': 'PLW', 'num_total_identities': 2, 'num_verified_identities': 0, 'num_suspicious_matches': 2}
{'imo': 9408542, 'found': True, 'current_name': 'SUVRETTA', 'current_flag': 'MHL', 'num_total_identities': 2, 'num_verified_identities': 1, 'num_suspicious_matches': 1}
{'imo': 9408190, 'found': True, 'current_name': 'GLORYCROWN', 'current_flag': 'MHL', 'num_total_identities': 4, 'num_verified_identities': 1, 'num_suspicious_matches': 3}
{'imo': 9439539, 'found': True, 'current_name': 'SEABAY', 'current_flag': 'HKG', 'num_total_identities': 4, 'num_verified_identities': 1, 'num_suspicious_matches': 3}
{'imo': 9436020, 'found': True, 'current_name': 'CRUDECENTURION', 'current_flag': 'MHL', 'num_total_identities': 2, 'num_verified_identities': 1, 'num_suspicious_matches': 1}
{'imo': 9213296, 'found': True, 'current_name': 'SEAWAYSSHIRLEY', 'current_flag': 'MHL', 'num_total_identities': 7, 'num_verified_identities': 1, 'num_suspicious_matches': 6}
{'imo': 9297541, 'found': True, 'current_name': 'BONITA', 'current_flag': 'GRC', 'num_total_identities': 3, 'num_verified_identities': 1, 'num_suspicious_matches': 2}
{'imo': 9412452, 'found': True, 'current_name': 'UNITEDFORTITUDE', 'current_flag': 'GRC', 'num_total_identities': 6, 'num_verified_identities': 1, 'num_suspicious_matches': 5}
{'imo': 9384564, 'found': True, 'current_name': 'REDSUN', 'current_flag': 'LBR', 'num_total_identities': 5, 'num_verified_identities': 1, 'num_suspicious_matches': 4}
{'imo': 9358412, 'found': True, 'current_name': 'TORMMATHILDE', 'current_flag': 'DNK', 'num_total_identities': 2, 'num_verified_identities': 1, 'num_suspicious_matches': 1}
{'imo': 9408683, 'found': True, 'current_name': 'ADVANTAGESOLAR', 'current_flag': 'MHL', 'num_total_identities': 4, 'num_verified_identities': 1, 'num_suspicious_matches': 3}
{'imo': 9389071, 'found': True, 'current_name': 'SCORPIO', 'current_flag': 'CYM', 'num_total_identities': 3, 'num_verified_identities': 1, 'num_suspicious_matches': 2}
{'imo': 9389083, 'found': True, 'current_name': 'AGRARI', 'current_flag': 'MLT', 'num_total_identities': 1, 'num_verified_identities': 1, 'num_suspicious_matches': 0}
{'imo': 9402328, 'found': True, 'current_name': 'KARASEA', 'current_flag': 'SGP', 'num_total_identities': 3, 'num_verified_identities': 1, 'num_suspicious_matches': 2}
{'imo': 9337341, 'found': True, 'current_name': 'YASAGOLDENMARMARA', 'current_flag': 'MHL', 'num_total_identities': 2, 'num_verified_identities': 1, 'num_suspicious_matches': 1}
{'imo': 9233777, 'found': True, 'current_name': 'BACALIAROS', 'current_flag': 'DEU', 'num_total_identities': 5, 'num_verified_identities': 1, 'num_suspicious_matches': 4}
{'imo': 9821469, 'found': True, 'current_name': 'LACHIN', 'current_flag': 'AZE', 'num_total_identities': 1, 'num_verified_identities': 0, 'num_suspicious_matches': 1}
{'imo': 9274525, 'found': True, 'current_name': 'NORDICRIO', 'current_flag': 'BHS', 'num_total_identities': 4, 'num_verified_identities': 2, 'num_suspicious_matches': 2}
{'imo': 9306809, 'found': True, 'current_name': 'NCCTABUK', 'current_flag': 'SAU', 'num_total_identities': 4, 'num_verified_identities': 1, 'num_suspicious_matches': 3}
{'imo': 9037123, 'found': True, 'current_name': 'ZHONGGANGDALIAN', 'current_flag': 'CHN', 'num_total_identities': 6, 'num_verified_identities': 1, 'num_suspicious_matches': 5}
{'imo': 9430272, 'found': True, 'current_name': 'ALPINEETERNITY', 'current_flag': 'SGP', 'num_total_identities': 5, 'num_verified_identities': 0, 'num_suspicious_matches': 5}
{'imo': 9321718, 'found': True, 'current_name': 'CAPPHILIPPE', 'current_flag': 'GRC', 'num_total_identities': 4, 'num_verified_identities': 1, 'num_suspicious_matches': 3}
{'imo': 9333577, 'found': True, 'current_name': 'GENERAL HAZI ASLANOV', 'current_flag': 'RUS', 'num_total_identities': 1, 'num_verified_identities': 0, 'num_suspicious_matches': 1}
{'imo': 9645023, 'found': True, 'current_name': 'VF TANKER-13', 'current_flag': 'RUS', 'num_total_identities': 1, 'num_verified_identities': 0, 'num_suspicious_matches': 1}
{'imo': 9645009, 'found': True, 'current_name': 'VF TANKER-11', 'current_flag': 'RUS', 'num_total_identities': 1, 'num_verified_identities': 0, 'num_suspicious_matches': 1}
{'imo': 9164718, 'found': True, 'current_name': 'TRANSHOLM', 'current_flag': 'MLT', 'num_total_identities': 3, 'num_verified_identities': 1, 'num_suspicious_matches': 2}
{'imo': 9735141, 'found': True, 'current_name': 'MIDVOLGA3', 'current_flag': 'RUS', 'num_total_identities': 2, 'num_verified_identities': 1, 'num_suspicious_matches': 1}
{'imo': 9046564, 'found': True, 'current_name': 'ANTARES', 'current_flag': 'RUS', 'num_total_identities': 1, 'num_verified_identities': 0, 'num_suspicious_matches': 1}
{'imo': 9503304, 'found': True, 'current_name': 'GENERAL SKOBELEV', 'current_flag': 'RUS', 'num_total_identities': 1, 'num_verified_identities': 0, 'num_suspicious_matches': 1}
{'imo': 9690212, 'found': True, 'current_name': 'STALINGRAD', 'current_flag': 'RUS', 'num_total_identities': 1, 'num_verified_identities': 0, 'num_suspicious_matches': 1}
{'imo': 9612909, 'found': True, 'current_name': 'ALEKSANDR SHEMAGIN', 'current_flag': 'RUS', 'num_total_identities': 1, 'num_verified_identities': 0, 'num_suspicious_matches': 1}
{'imo': 9292199, 'found': True, 'current_name': 'BESIKTASDARDANELLES', 'current_flag': 'TUR', 'num_total_identities': 7, 'num_verified_identities': 1, 'num_suspicious_matches': 6}
{'imo': 9347308, 'found': True, 'current_name': 'CPOFRANCE', 'current_flag': 'DEU', 'num_total_identities': 4, 'num_verified_identities': 1, 'num_suspicious_matches': 3}
{'imo': 9290373, 'found': True, 'current_name': 'BESIKTASBOSPHORUS', 'current_flag': 'TUR', 'num_total_identities': 6, 'num_verified_identities': 1, 'num_suspicious_matches': 5}
{'imo': 9867621, 'found': True, 'current_name': 'KHANKENDI', 'current_flag': 'AZE', 'num_total_identities': 2, 'num_verified_identities': 1, 'num_suspicious_matches': 1}
{'imo': 9621596, 'found': True, 'current_name': 'BORABORA', 'current_flag': 'MLT', 'num_total_identities': 2, 'num_verified_identities': 1, 'num_suspicious_matches': 1}
{'imo': 9645047, 'found': True, 'current_name': 'VF TANKER-15', 'current_flag': 'RUS', 'num_total_identities': 1, 'num_verified_identities': 0, 'num_suspicious_matches': 1}
{'imo': 9884150, 'found': True, 'current_name': 'SERGEY LVOV', 'current_flag': 'RUS', 'num_total_identities': 2, 'num_verified_identities': 0, 'num_suspicious_matches': 2}
{'imo': 9640580, 'found': True, 'current_name': 'CONSTRUCTOR ZHIVOTOVSKY', 'current_flag': 'RUS', 'num_total_identities': 1, 'num_verified_identities': 0, 'num_suspicious_matches': 1}
{'imo': 9645035, 'found': True, 'current_name': 'VF TANKER-14', 'current_flag': 'RUS', 'num_total_identities': 1, 'num_verified_identities': 0, 'num_suspicious_matches': 1}

In [25]:
for b in all_identities_full:
    print(b)

{'imo': 9328170, 'shipname': 'AETHER', 'flag': 'PAN', 'ssvid': '352002230', 'match_fields': 'REGISTRY', 'transmission_from': '2023-01-23T14:38:25Z', 'transmission_to': '2025-10-06T11:09:01Z', 'is_verified': False}
{'imo': 9328170, 'shipname': 'WAFRAH', 'flag': 'KWT', 'ssvid': '447162000', 'match_fields': 'REGISTRY', 'transmission_from': '2012-01-08T14:12:44Z', 'transmission_to': '2022-05-10T11:17:25Z', 'is_verified': True}
{'imo': 9328170, 'shipname': 'AETHER', 'flag': 'MDG', 'ssvid': '647553007', 'match_fields': 'NO_MATCH', 'transmission_from': '2026-03-14T15:43:17Z', 'transmission_to': '2026-05-19T14:51:02Z', 'is_verified': False}
{'imo': 9328170, 'shipname': 'AETHER', 'flag': 'GIN', 'ssvid': '632001155', 'match_fields': 'NO_MATCH', 'transmission_from': '2025-10-06T11:17:25Z', 'transmission_to': '2026-03-14T15:49:37Z', 'is_verified': False}
{'imo': 9328170, 'shipname': 'AETHER', 'flag': 'CMR', 'ssvid': '613442802', 'match_fields': 'NO_MATCH', 'transmission_from': '2026-05-19T14:56:47Z', 'transmission_to': '2026-05-20T07:55:53Z', 'is_verified': False}
{'imo': 9328170, 'shipname': 'LILA FUJAIRAH', 'flag': 'LBR', 'ssvid': '636021839', 'match_fields': 'NO_MATCH', 'transmission_from': '2022-05-10T11:31:35.73Z', 'transmission_to': '2023-02-18T05:12:21Z', 'is_verified': False}
{'imo': 9328170, 'shipname': 'AETHER', 'flag': 'CMR', 'ssvid': '613442803', 'match_fields': 'NO_MATCH', 'transmission_from': '2026-05-20T08:24:58Z', 'transmission_to': '2026-08-14T23:59:58Z', 'is_verified': False}
{'imo': 9282481, 'shipname': 'TAGOR', 'flag': 'PAN', 'ssvid': '352002249', 'match_fields': 'REGISTRY', 'transmission_from': '2024-07-06T08:23:17Z', 'transmission_to': '2025-09-12T05:12:57Z', 'is_verified': False}
{'imo': 9282481, 'shipname': 'BRITISHGANNET', 'flag': 'IMN', 'ssvid': '232150000', 'match_fields': 'REGISTRY', 'transmission_from': '2012-01-13T03:59:15Z', 'transmission_to': '2018-12-12T13:10:10Z', 'is_verified': True}
{'imo': 9282481, 'shipname': 'PIPER', 'flag': 'MHL', 'ssvid': '538008199', 'match_fields': 'NO_MATCH', 'transmission_from': '2018-12-12T13:16:50Z', 'transmission_to': '2023-02-04T23:21:30Z', 'is_verified': False}
{'imo': 9282481, 'shipname': 'TAGOR', 'flag': 'CMR', 'ssvid': '613442790', 'match_fields': 'NO_MATCH', 'transmission_from': '2026-05-26T10:02:57Z', 'transmission_to': '2026-08-14T23:57:07Z', 'is_verified': False}
{'imo': 9282481, 'shipname': 'TAGOR', 'flag': 'MDG', 'ssvid': '647260300', 'match_fields': 'NO_MATCH', 'transmission_from': '2026-03-17T05:45:02Z', 'transmission_to': '2026-05-26T08:33:12Z', 'is_verified': False}
{'imo': 9282481, 'shipname': 'TAGOR', 'flag': 'GIN', 'ssvid': '632001144', 'match_fields': 'NO_MATCH', 'transmission_from': '2025-09-15T11:54:24Z', 'transmission_to': '2026-03-17T05:41:01Z', 'is_verified': False}
{'imo': 9282481, 'shipname': 'PRIAPUS', 'flag': 'NIC', 'ssvid': '350002249', 'match_fields': 'NO_MATCH', 'transmission_from': '2023-04-03T12:56:44Z', 'transmission_to': '2023-06-11T06:36:00Z', 'is_verified': False}
{'imo': 9282481, 'shipname': 'FRENCH NAVY WARSHIP', 'flag': 'FRA', 'ssvid': '228741000', 'match_fields': 'NO_MATCH', 'transmission_from': '2012-03-13T17:13:44Z', 'transmission_to': '2012-03-21T06:01:13Z', 'is_verified': False}
{'imo': 9236248, 'shipname': 'MINERVAZENIA', 'flag': 'GRC', 'ssvid': '374635000', 'match_fields': 'REGISTRY', 'transmission_from': '2021-01-04T05:31:34Z', 'transmission_to': '2022-08-07T16:03:06Z', 'is_verified': True}
{'imo': 9236248, 'shipname': 'PHOENIX1', 'flag': 'COK', 'ssvid': '518999317', 'match_fields': 'REGISTRY', 'transmission_from': '2024-10-09T07:58:03Z', 'transmission_to': '2025-03-20T10:48:28Z', 'is_verified': False}
{'imo': 9236248, 'shipname': 'FENGHUANG', 'flag': 'MOZ', 'ssvid': '650000127', 'match_fields': 'NO_MATCH', 'transmission_from': '2026-03-23T08:45:55Z', 'transmission_to': '2026-08-14T23:51:31Z', 'is_verified': False}
{'imo': 9236248, 'shipname': 'FENGHUANG', 'flag': 'COM', 'ssvid': '620999873', 'match_fields': 'NO_MATCH', 'transmission_from': '2025-05-06T11:06:09Z', 'transmission_to': '2026-01-07T05:40:18Z', 'is_verified': False}
{'imo': 9236248, 'shipname': 'FENGHUANG', 'flag': 'MDG', 'ssvid': '647553034', 'match_fields': 'NO_MATCH', 'transmission_from': '2026-01-07T05:36:59Z', 'transmission_to': '2026-03-04T16:56:24Z', 'is_verified': False}
{'imo': 9236248, 'shipname': 'FENGHUANG', 'flag': 'CMR', 'ssvid': '613471210', 'match_fields': 'NO_MATCH', 'transmission_from': '2026-03-04T17:08:23Z', 'transmission_to': '2026-03-23T08:40:01Z', 'is_verified': False}
{'imo': 9236248, 'shipname': 'FENGHUANG', 'flag': 'BES', 'ssvid': '306100000', 'match_fields': 'NO_MATCH', 'transmission_from': '2025-03-20T10:49:25Z', 'transmission_to': '2025-05-06T11:01:16Z', 'is_verified': False}
{'imo': 9439383, 'shipname': 'ONIKS', 'flag': 'RUS', 'ssvid': '273121120', 'match_fields': 'NO_MATCH', 'transmission_from': '2026-07-22T07:03:07Z', 'transmission_to': '2026-08-14T23:59:15Z', 'is_verified': False}
{'imo': 9439383, 'shipname': 'PS GENOVA', 'flag': 'MLT', 'ssvid': '229903000', 'match_fields': 'NO_MATCH', 'transmission_from': '2022-03-21T13:41:21Z', 'transmission_to': '2024-12-02T02:22:09Z', 'is_verified': False}
{'imo': 9439383, 'shipname': 'GIOVANNIBATTISTADECARLINI', 'flag': 'ITA', 'ssvid': '247287800', 'match_fields': 'REGISTRY', 'transmission_from': '2018-05-23T17:13:29Z', 'transmission_to': '2020-02-02T01:56:28Z', 'is_verified': True}
{'imo': 9439383, 'shipname': 'BHILVA', 'flag': 'PAN', 'ssvid': '352004905', 'match_fields': 'NO_MATCH', 'transmission_from': '2024-12-02T02:26:09Z', 'transmission_to': '2026-05-23T00:48:45Z', 'is_verified': False}
{'imo': 9311610, 'shipname': 'MILTIADISM2', 'flag': 'LBR', 'ssvid': '636012728', 'match_fields': 'REGISTRY', 'transmission_from': '2012-01-01T00:08:48Z', 'transmission_to': '2021-08-06T08:11:24Z', 'is_verified': True}
{'imo': 9311610, 'shipname': 'TORX', 'flag': 'GNQ', 'ssvid': '631010109', 'match_fields': 'NO_MATCH', 'transmission_from': '2026-07-16T12:50:12Z', 'transmission_to': '2026-08-14T22:04:12Z', 'is_verified': False}
{'imo': 9311610, 'shipname': 'TORX', 'flag': 'PAN', 'ssvid': '352005255', 'match_fields': 'NO_MATCH', 'transmission_from': '2025-02-21T14:29:34Z', 'transmission_to': '2026-07-16T12:40:54Z', 'is_verified': False}
{'imo': 9472634, 'shipname': 'AURA 1', 'flag': 'PAN', 'ssvid': '352005472', 'match_fields': 'NO_MATCH', 'transmission_from': '2025-04-08T11:25:29Z', 'transmission_to': '2026-08-14T23:59:44Z', 'is_verified': False}
{'imo': 9472634, 'shipname': 'ADVANTAGEANTHEM', 'flag': 'MHL', 'ssvid': '538006199', 'match_fields': 'REGISTRY', 'transmission_from': '2015-05-13T01:41:27Z', 'transmission_to': '2022-04-27T11:55:18Z', 'is_verified': True}
{'imo': 9460564, 'shipname': 'KALAMAS', 'flag': 'LBR', 'ssvid': '538009165', 'match_fields': 'REGISTRY', 'transmission_from': '2020-12-20T20:06:17Z', 'transmission_to': '2020-12-22T15:04:18Z', 'is_verified': True}
{'imo': 9460564, 'shipname': 'BALU 6', 'flag': 'PAN', 'ssvid': '352005437', 'match_fields': 'NO_MATCH', 'transmission_from': '2025-04-02T10:50:53Z', 'transmission_to': '2026-08-14T23:58:59Z', 'is_verified': False}
{'imo': 9419450, 'shipname': 'ADVANTAGEAVENUE', 'flag': 'MHL', 'ssvid': '538006203', 'match_fields': 'REGISTRY', 'transmission_from': '2015-04-04T17:29:41Z', 'transmission_to': '2022-05-11T11:04:50Z', 'is_verified': True}
{'imo': 9419450, 'shipname': 'JEWEL', 'flag': 'PAN', 'ssvid': '374987000', 'match_fields': 'NO_MATCH', 'transmission_from': '2025-04-09T09:33:12Z', 'transmission_to': '2026-08-14T23:57:16Z', 'is_verified': False}
{'imo': 9419450, 'shipname': 'JEWEL', 'flag': 'PAN', 'ssvid': '374957000', 'match_fields': 'NO_MATCH', 'transmission_from': '2025-04-09T08:15:57Z', 'transmission_to': '2025-04-09T09:31:14Z', 'is_verified': False}
{'imo': 9299707, 'shipname': 'GUANYIN', 'flag': 'LBR', 'ssvid': '632001154', 'match_fields': 'REGISTRY', 'transmission_from': '2025-10-10T03:41:04Z', 'transmission_to': '2025-10-10T19:51:35Z', 'is_verified': False}
{'imo': 9299707, 'shipname': 'GUANYIN', 'flag': 'LBR', 'ssvid': '636012383', 'match_fields': 'REGISTRY', 'transmission_from': '2022-05-14T08:03:04Z', 'transmission_to': '2025-10-07T03:54:17Z', 'is_verified': False}
{'imo': 9299707, 'shipname': 'GUANYIN', 'flag': 'MDG', 'ssvid': '647553008', 'match_fields': 'NO_MATCH', 'transmission_from': '2026-03-08T12:43:31Z', 'transmission_to': '2026-06-03T05:03:18Z', 'is_verified': False}
{'imo': 9299707, 'shipname': 'GUANYIN', 'flag': 'CMR', 'ssvid': '613442815', 'match_fields': 'NO_MATCH', 'transmission_from': '2026-06-03T05:02:25Z', 'transmission_to': '2026-07-05T19:17:34Z', 'is_verified': False}
{'imo': 9299707, 'shipname': 'NSCONCEPT', 'flag': 'LBR', 'ssvid': '636012383', 'match_fields': 'REGISTRY', 'transmission_from': '2012-01-01T00:03:10Z', 'transmission_to': '2022-05-28T15:46:05Z', 'is_verified': False}
{'imo': 9296377, 'shipname': 'MARJORIE', 'flag': 'BRB', 'ssvid': '314001095', 'match_fields': 'NO_MATCH', 'transmission_from': '2025-04-15T08:56:30Z', 'transmission_to': '2025-11-02T11:08:19Z', 'is_verified': False}
{'imo': 9296377, 'shipname': 'CHIOS', 'flag': 'MHL', 'ssvid': '538011642', 'match_fields': 'NO_MATCH', 'transmission_from': '2025-04-10T12:00:35Z', 'transmission_to': '2025-04-15T08:53:47Z', 'is_verified': False}
{'imo': 9296377, 'shipname': 'TOKYOSPIRIT', 'flag': 'BHS', 'ssvid': '311000453', 'match_fields': 'REGISTRY', 'transmission_from': '2015-10-06T21:07:39Z', 'transmission_to': '2025-04-10T11:55:16Z', 'is_verified': True}
{'imo': 9296377, 'shipname': 'MARJORIE', 'flag': 'VUT', 'ssvid': '577678000', 'match_fields': 'NO_MATCH', 'transmission_from': '2025-10-13T12:12:54Z', 'transmission_to': '2026-05-25T11:16:20Z', 'is_verified': False}
{'imo': 9296377, 'shipname': 'MARJORIE', 'flag': 'SLE', 'ssvid': '667001954', 'match_fields': 'NO_MATCH', 'transmission_from': '2026-05-25T11:16:29Z', 'transmission_to': '2026-08-14T23:58:56Z', 'is_verified': False}
{'imo': 9224453, 'shipname': 'MARS A', 'flag': 'PLW', 'ssvid': '511100876', 'match_fields': 'REGISTRY', 'transmission_from': '2022-12-13T13:20:21Z', 'transmission_to': '2024-06-04T03:23:44Z', 'is_verified': False}
{'imo': 9224453, 'shipname': 'TRACOS', 'flag': 'SMR', 'ssvid': '268263502', 'match_fields': 'NO_MATCH', 'transmission_from': '2026-07-11T18:36:29Z', 'transmission_to': '2026-08-14T23:58:38Z', 'is_verified': False}
{'imo': 9408542, 'shipname': 'TONG TU', 'flag': 'SLE', 'ssvid': '667001512', 'match_fields': 'NO_MATCH', 'transmission_from': '2026-06-18T04:53:14Z', 'transmission_to': '2026-08-14T23:46:20Z', 'is_verified': False}
{'imo': 9408542, 'shipname': 'SUVRETTA', 'flag': 'MHL', 'ssvid': '352005116', 'match_fields': 'REGISTRY', 'transmission_from': '2025-01-18T16:29:39Z', 'transmission_to': '2025-01-23T05:40:56Z', 'is_verified': True}
{'imo': 9408190, 'shipname': 'GLORYCROWN', 'flag': 'MHL', 'ssvid': '538005144', 'match_fields': 'REGISTRY', 'transmission_from': '2013-05-29T03:09:32Z', 'transmission_to': '2023-03-10T11:06:04Z', 'is_verified': True}
{'imo': 9408190, 'shipname': 'SAMOS', 'flag': 'BRB', 'ssvid': '314001145', 'match_fields': 'NO_MATCH', 'transmission_from': '2025-08-16T10:06:02Z', 'transmission_to': '2025-11-17T08:25:56Z', 'is_verified': False}
{'imo': 9408190, 'shipname': 'SAMOS', 'flag': 'LBR', 'ssvid': '636022763', 'match_fields': 'NO_MATCH', 'transmission_from': '2023-03-10T11:31:35Z', 'transmission_to': '2025-08-16T09:58:12Z', 'is_verified': False}
{'imo': 9408190, 'shipname': 'SAMOS', 'flag': 'CMR', 'ssvid': '613271810', 'match_fields': 'NO_MATCH', 'transmission_from': '2025-11-17T13:11:52Z', 'transmission_to': '2026-08-14T23:57:30Z', 'is_verified': False}
{'imo': 9439539, 'shipname': 'SEABAY', 'flag': 'HKG', 'ssvid': '477170700', 'match_fields': 'REGISTRY', 'transmission_from': '2012-01-04T09:23:13Z', 'transmission_to': '2023-08-17T10:42:43Z', 'is_verified': True}
{'imo': 9439539, 'shipname': 'BOLU', 'flag': 'BRB', 'ssvid': '314001144', 'match_fields': 'NO_MATCH', 'transmission_from': '2025-08-18T07:25:30Z', 'transmission_to': '2025-11-13T12:57:12Z', 'is_verified': False}
{'imo': 9439539, 'shipname': 'BOLU', 'flag': 'CMR', 'ssvid': '613271610', 'match_fields': 'NO_MATCH', 'transmission_from': '2025-11-13T12:57:44Z', 'transmission_to': '2026-08-14T23:58:40Z', 'is_verified': False}
{'imo': 9439539, 'shipname': 'BOLU', 'flag': 'LBR', 'ssvid': '636022767', 'match_fields': 'NO_MATCH', 'transmission_from': '2023-08-17T10:47:47Z', 'transmission_to': '2025-08-20T17:25:25Z', 'is_verified': False}
{'imo': 9436020, 'shipname': 'CRUDECENTURION', 'flag': 'MHL', 'ssvid': '538003868', 'match_fields': 'REGISTRY', 'transmission_from': '2017-02-09T11:47:02Z', 'transmission_to': '2025-02-19T09:13:50Z', 'is_verified': True}
{'imo': 9436020, 'shipname': 'CENTURION I', 'flag': 'PAN', 'ssvid': '352005238', 'match_fields': 'NO_MATCH', 'transmission_from': '2025-02-19T09:28:52Z', 'transmission_to': '2026-08-14T23:59:54Z', 'is_verified': False}
{'imo': 9213296, 'shipname': 'SHIRLEY', 'flag': 'LBR', 'ssvid': '636019026', 'match_fields': 'NO_MATCH', 'transmission_from': '2018-12-01T07:58:07Z', 'transmission_to': '2019-06-12T23:58:13Z', 'is_verified': False}
{'imo': 9213296, 'shipname': 'SEAWAYSSHIRLEY', 'flag': 'MHL', 'ssvid': '538004852', 'match_fields': 'REGISTRY', 'transmission_from': '2017-10-02T21:34:28Z', 'transmission_to': '2018-11-01T14:10:29Z', 'is_verified': True}
{'imo': 9213296, 'shipname': 'US SHIRLEY', 'flag': 'COM', 'ssvid': '620321000', 'match_fields': 'NO_MATCH', 'transmission_from': '2018-11-02T02:54:00Z', 'transmission_to': '2018-12-01T07:41:09Z', 'is_verified': False}
{'imo': 9213296, 'shipname': 'BRIGHTSONIA', 'flag': 'PAN', 'ssvid': '351660000', 'match_fields': 'REGISTRY', 'transmission_from': '2019-05-18T08:39:13Z', 'transmission_to': '2024-10-02T11:38:42Z', 'is_verified': False}
{'imo': 9213296, 'shipname': 'TELESTO', 'flag': 'PLW', 'ssvid': '511101917', 'match_fields': 'NO_MATCH', 'transmission_from': '2025-11-22T20:29:06Z', 'transmission_to': '2026-08-14T23:58:51Z', 'is_verified': False}
{'imo': 9213296, 'shipname': 'TELESTO', 'flag': 'GIN', 'ssvid': '632001104', 'match_fields': 'NO_MATCH', 'transmission_from': '2024-10-02T12:46:42Z', 'transmission_to': '2025-01-09T03:24:35Z', 'is_verified': False}
{'imo': 9213296, 'shipname': 'TELESTO', 'flag': 'BRB', 'ssvid': '314001023', 'match_fields': 'NO_MATCH', 'transmission_from': '2025-01-09T03:28:03Z', 'transmission_to': '2025-11-22T10:48:56Z', 'is_verified': False}
{'imo': 9297541, 'shipname': 'BONITA', 'flag': 'GRC', 'ssvid': '240609000', 'match_fields': 'REGISTRY', 'transmission_from': '2012-01-01T00:08:38Z', 'transmission_to': '2022-07-04T04:35:18Z', 'is_verified': True}
{'imo': 9297541, 'shipname': 'BONITA', 'flag': 'MHL', 'ssvid': '538009978', 'match_fields': 'NO_MATCH', 'transmission_from': '2022-07-04T10:51:22.41Z', 'transmission_to': '2025-03-04T14:20:45Z', 'is_verified': False}
{'imo': 9297541, 'shipname': 'DOVE', 'flag': 'PAN', 'ssvid': '352005301', 'match_fields': 'NO_MATCH', 'transmission_from': '2025-03-04T14:23:41Z', 'transmission_to': '2026-08-14T23:57:50Z', 'is_verified': False}
{'imo': 9412452, 'shipname': 'UNITEDFORTITUDE', 'flag': 'GRC', 'ssvid': '240952000', 'match_fields': 'REGISTRY', 'transmission_from': '2012-01-14T08:51:00Z', 'transmission_to': '2018-10-05T10:32:07Z', 'is_verified': True}
{'imo': 9412452, 'shipname': 'NILANGA', 'flag': 'GNQ', 'ssvid': '631010070', 'match_fields': 'NO_MATCH', 'transmission_from': '2026-05-20T14:25:10Z', 'transmission_to': '2026-08-11T18:42:34Z', 'is_verified': False}
{'imo': 9412452, 'shipname': 'ELLI', 'flag': 'MHL', 'ssvid': '538008046', 'match_fields': 'NO_MATCH', 'transmission_from': '2018-10-05T11:40:12Z', 'transmission_to': '2025-01-05T01:02:55Z', 'is_verified': False}
{'imo': 9412452, 'shipname': 'TSOIZIT', 'flag': 'RUS', 'ssvid': '273127920', 'match_fields': 'NO_MATCH', 'transmission_from': '2026-08-10T09:39:48Z', 'transmission_to': '2026-08-14T23:59:59Z', 'is_verified': False}
{'imo': 9412452, 'shipname': 'NILANGA', 'flag': 'PAN', 'ssvid': '352004926', 'match_fields': 'NO_MATCH', 'transmission_from': '2024-12-07T07:16:52Z', 'transmission_to': '2025-12-13T10:43:12Z', 'is_verified': False}
{'imo': 9412452, 'shipname': 'NILANGA', 'flag': 'SLE', 'ssvid': '667001290', 'match_fields': 'NO_MATCH', 'transmission_from': '2025-12-05T16:34:25Z', 'transmission_to': '2026-05-20T14:26:44Z', 'is_verified': False}
{'imo': 9384564, 'shipname': 'SEARUN', 'flag': 'PLW', 'ssvid': '511101911', 'match_fields': 'NO_MATCH', 'transmission_from': '2025-11-08T09:32:57Z', 'transmission_to': '2026-01-20T06:46:31Z', 'is_verified': False}
{'imo': 9384564, 'shipname': 'REDSUN', 'flag': 'LBR', 'ssvid': '636017066', 'match_fields': 'REGISTRY', 'transmission_from': '2015-10-13T14:00:52Z', 'transmission_to': '2025-03-26T15:41:01Z', 'is_verified': True}
{'imo': 9384564, 'shipname': 'NORTH SEA', 'flag': 'SGP', 'ssvid': '564369000', 'match_fields': 'NO_MATCH', 'transmission_from': '2012-01-03T17:27:39Z', 'transmission_to': '2013-08-22T05:44:33Z', 'is_verified': False}
{'imo': 9384564, 'shipname': 'SEARUN', 'flag': 'HKG', 'ssvid': '477140500', 'match_fields': 'NO_MATCH', 'transmission_from': '2025-03-26T15:45:21Z', 'transmission_to': '2025-11-10T03:46:15Z', 'is_verified': False}
{'imo': 9384564, 'shipname': 'SEARUN', 'flag': 'BRB', 'ssvid': '314001157', 'match_fields': 'NO_MATCH', 'transmission_from': '2026-01-20T06:46:25Z', 'transmission_to': '2026-08-14T23:57:46Z', 'is_verified': False}
{'imo': 9358412, 'shipname': 'TORMMATHILDE', 'flag': 'DNK', 'ssvid': '220629000', 'match_fields': 'REGISTRY', 'transmission_from': '2012-03-26T07:17:41Z', 'transmission_to': '2025-05-22T03:38:31Z', 'is_verified': True}
{'imo': 9358412, 'shipname': 'TIGER WINGS', 'flag': 'PAN', 'ssvid': '352005654', 'match_fields': 'NO_MATCH', 'transmission_from': '2025-05-22T03:44:37Z', 'transmission_to': '2026-08-14T23:59:09Z', 'is_verified': False}
{'imo': 9408683, 'shipname': 'ADVANTAGESOLAR', 'flag': 'MHL', 'ssvid': '538006200', 'match_fields': 'REGISTRY', 'transmission_from': '2015-02-16T16:48:19Z', 'transmission_to': '2025-05-15T04:58:25Z', 'is_verified': True}
{'imo': 9408683, 'shipname': 'ZHUO YUAN', 'flag': 'PAN', 'ssvid': '352005826', 'match_fields': 'NO_MATCH', 'transmission_from': '2025-08-05T13:44:48Z', 'transmission_to': '2025-08-21T07:41:24Z', 'is_verified': False}
{'imo': 9408683, 'shipname': 'P 74', 'flag': 'ESP', 'ssvid': '224803000', 'match_fields': 'NO_MATCH', 'transmission_from': '2015-06-20T00:06:55Z', 'transmission_to': '2015-06-22T19:07:37Z', 'is_verified': False}
{'imo': 9408683, 'shipname': 'ZHUO YUAN', 'flag': 'PAN', 'ssvid': '352005626', 'match_fields': 'NO_MATCH', 'transmission_from': '2025-05-15T05:06:58Z', 'transmission_to': '2026-08-14T07:50:05Z', 'is_verified': False}
{'imo': 9389071, 'shipname': 'SCORPIO', 'flag': 'CYM', 'ssvid': '319129600', 'match_fields': 'REGISTRY', 'transmission_from': '2017-12-13T07:33:00Z', 'transmission_to': '2025-03-21T12:14:32Z', 'is_verified': True}
{'imo': 9389071, 'shipname': 'TANGO 2', 'flag': 'PAN', 'ssvid': '352005354', 'match_fields': 'NO_MATCH', 'transmission_from': '2025-03-21T14:01:17Z', 'transmission_to': '2026-08-14T23:59:50Z', 'is_verified': False}
{'imo': 9389071, 'shipname': 'SCORPIO', 'flag': 'GRC', 'ssvid': '240864000', 'match_fields': 'NO_MATCH', 'transmission_from': '2012-01-21T07:00:08Z', 'transmission_to': '2019-04-01T09:23:15Z', 'is_verified': False}
{'imo': 9389083, 'shipname': 'AGRARI', 'flag': 'MLT', 'ssvid': '352005486', 'match_fields': 'REGISTRY', 'transmission_from': '2025-07-10T07:44:15Z', 'transmission_to': '2025-08-07T20:04:57Z', 'is_verified': True}
{'imo': 9402328, 'shipname': 'KARASEA', 'flag': 'SGP', 'ssvid': '564870000', 'match_fields': 'REGISTRY', 'transmission_from': '2012-01-07T21:47:59Z', 'transmission_to': '2025-03-06T04:01:50Z', 'is_verified': True}

In [26]:
summary_df = pd.DataFrame(all_summaries)
identities_df = pd.DataFrame(all_identities_full)

print(summary_df.shape)
print(identities_df.shape)
summary_df.head()

(50, 7)
(163, 8)

,imo,found,current_name,current_flag,num_total_identities,num_verified_identities,num_suspicious_matches
0,9328170,True,WAFRAH,KWT,7,1,6
1,9282481,True,BRITISHGANNET,IMN,8,1,7
2,9236248,True,MINERVAZENIA,GRC,7,1,6
3,9439383,True,GIOVANNIBATTISTADECARLINI,ITA,4,1,3
4,9311610,True,MILTIADISM2,LBR,3,1,2

In [27]:
identities_df['flag'].value_counts()

flag
PAN    24
MHL    20
RUS    17
LBR    16
CMR    11
MLT     6
SLE     6
GRC     5
BRB     5
MDG     4
HKG     4
GIN     3
COM     3
BHS     3
PLW     3
SGP     3
NIC     2
GNQ     2
DEU     2
AZE     2
CHN     2
TUR     2
KWT     1
IMN     1
FRA     1
COK     1
MOZ     1
BES     1
ITA     1
VUT     1
SMR     1
DNK     1
ESP     1
CYM     1
ATG     1
CYP     1
SAU     1
SYR     1
Name: count, dtype: int64

In [28]:
summary_df['num_suspicious_matches'].describe()

count    50.00000
mean      2.54000
std       1.82063
min       0.00000
25%       1.00000
50%       2.00000
75%       3.75000
max       7.00000
Name: num_suspicious_matches, dtype: float64